export interface Character {
   id: string                   ;  // '唯一标识'
   book_id: string              ; // 'www_book唯一标识'
   character_first_name: string ;  // '角色首名'
   character_mid_name: string   ;  // '角色中间名'
   character_last_name: string  ;  // '角色姓氏'
   character_full_name: string  ;  // '角色全名'
   character_nickname: string   ;  // '角色昵称'
   character_gender: string     ; // '性别'
   character_age: number        ;  // '年龄'
   character_birthday: string   ;  // '生日'
   species: string              ;  // '物种'
   occupation: string           ;  // '职业'
   main_character_flag: string  ; // '是否主角'
   character_status: string     ; // '状态'
   character_remark: string     ; //'备注'
   character_personality: string; //'性格描述'
   create_time: number          ;  // '创建时间'
   update_time: number          ;  // '最后编辑时间'
}